# Generated by Django 4.1 on 2024-04-01 17:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_parent"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendance",
            options={"ordering": ["-date", "student__register_number"]},
        ),
        migrations.AlterModelOptions(
            name="exam",
            options={"ordering": ["subject__class_related", "name"]},
        ),
        migrations.AlterModelOptions(
            name="result",
            options={"ordering": ["exam"]},
        ),
        migrations.AlterModelOptions(
            name="timetable",
            options={"ordering": ["start_time"]},
        ),
        migrations.RemoveField(
            model_name="exam",
            name="exam_id",
        ),
        migrations.DeleteModel(
            name="Break",
        ),
    ]
